name: 'ESP-IDF build'
description: 'Building ESP-IDF projects'
inputs:
   IDF_TARGET:
     description: 'Target device'
     required: true
     default: esp32
runs:
  using: 'docker'
  image: 'docker://espressif/idf:v4.4.3'
  args:
     - idf.py 
     - build
 
